# 서버 포트 설정
server:
  port: 8082

# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crud?serverTimezone=Asia/Seoul
    username: root
    password: bean981204

  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  # naver, kakao 자동 로그인
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: sls02okjQAPpWdDz3_xm
            client-secret: aEAR7TcEYi
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            scope:
              - name
              - email
            client-name: Naver

          kakao:
            client-id:
            client-secret:
            client-authentication-method:
            authorization-grant-type:
            scope:
              -profile_nickname
              -profile_image

            redirect-url:
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri:
            token-uri:
            user-info-uri:
            user-name-attribute:
            user-info-authentication-method:

logging:
  level:
    root=DEBUG:

jwk:
  secret: my-super-secret-jwt-signing-key